vexpenses_agenda/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Jobs\SendEmailJob;
use App\Mail\SendEmail;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::prefix('schedule/')->name('schedule.')->namespace('Schedule')->group(function () {

    Route::resource('categories', 'CategoryController');

    Route::resource('phones', 'PhoneController');

    Route::resource('adresses', 'AddressController');

    Route::resource('contacts', 'ContactController');

    Route::post('photos/remove/{contactId}', 'ContactController@removePhoto')->name('photo.remove');

    Route::get('exports', 'ContactController@exportContacts')->name('contacts.export');

    Route::get('print', 'ContactController@printPdf')->name('contacts.print');

    Route::get('contactsByDate', 'ContactController@showContactByDate')->name('contacts.byDate');

   

});

vexpenses_agenda/app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table = 'contacts';

    protected $fillable = [
       'name', 'email', 'user_id', 'category_id', 'image',
    ];

    public function address()
    {
        return $this->hasMany(Address::class);
    }

    public function phone()
    {
        return $this->hasMany(Phone::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_user');
    }
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/AddressController.php
<?php

namespace App\Http\Controllers\Schedule;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestAddressEdit;
use App\Services\AddressService;
use App\Services\ContactService;
use Illuminate\Http\Request;

class AddressController extends Controller
{

    protected $addressService;

    protected $userService;

    protected $contactService;
   
     /**
     * Construtor
     */
    public function __construct(AddressService $addressService, ContactService $contactService)
    {
         $this->addressService = $addressService;

         $this->contactService = $contactService;
    }
  

    /**
     * Retorna a visualização dos endereços de um usuário
     *
     * @param int $userId
     *
     * @return View
     */
    public function show($contactId)
    {
        $adresses = $this->addressService->findAddressByContact($contactId);

        $contact = $this->contactService->findContact($contactId);

        return view('schedule.adresses.index', compact('adresses', 'contact'));
    }

     /**
     * Retorna a visualização do formulário para edição de determinado endereço
     *
     * @param int $addressId
     *
     * @return void
     */
    public function edit($addressId)
    {
        $address = $this->addressService->findAddress($addressId);

        return view('schedule.adresses.edit', compact('address'));
    }

   /**
     * Atualiza um determinado endereço no banco
     *
     * @param int $addressId
     *
     * @param Request $request
     *
     * @return View
     */
    public function update(RequestAddressEdit $request, $addressId)
    {
        $data = $request->all();

        $this->addressService->updateAddress($data, $addressId);

        flash('Endereço Atualizado com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Exclui um determinado endereço no banco
     *
     * @param int $addressId
     *
     * @return View
     */
    public function destroy($addressId)
    {
        $this->addressService->deleteAddress($addressId);

        flash('Endereço Excluído com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/CategoryController.php
<?php

namespace App\Http\Controllers\Schedule;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestCategory;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use App\Http\Middleware\CheckContact;

class CategoryController extends Controller
{
     private $categoryService;
    
    /**
    * Construtor
    */
    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;

        $this->middleware('checkContact', ['only' => ['destroy']]);

        $this->middleware('checkCategoryName', ['only' => ['store','update']]);
    }

    /**
     * Retorna a visualização de todas as categorias existentes no banco
     *
     * @param
     *
     * @return View
     */
    public function index()
    {
        $categories = $this->categoryService->findAllCategories();

        return view('schedule.categories.index', compact('categories'));
    }

    /**
     * Retorna o formulário de criação das categorias
     *
     * @param
     *
     * @return View
     */
    public function create()
    {
        return view('schedule.categories.create');
    }

    /**
     * Salva a categoria no banco
     *
     * @param Request $request
     *
     * @return View
     */
    public function store(RequestCategory $request)
    {
         
          $data = $request->all();

          $this->categoryService->createCategory($data);

          flash('Categoria cadastrada com sucesso!')->success();

          return redirect()->route('schedule.categories.index');
    }


   
     /**
     * Retorna a visualização do formulário para edição de determinada categoria
     *
     * @param int $category
     *
     * @return void
     */
    public function edit($category)
    {
        $category = $this->categoryService->findCategory($category);

        return view('schedule.categories.edit', compact('category'));
    }

    /**
     * Atualiza determinada categoria no banco
     *
     * @param Request $request
     *
     * @param int $id
     *
     * @return View
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $this->categoryService->updateCategory($data, $id);

        flash('Categoria Atualizada com sucesso!')->success();

        return redirect()->route('schedule.categories.index');
    }

   /**
     * Exclui determinada categoria do banco de dados
     *
     * @param int $id
     *
     * @return View
     */
    public function destroy($id)
    {
        $this->categoryService->deleteCategory($id);

        flash('Categoria Excluida com Sucesso!')->success();

        return redirect()->route('schedule.categories.index');
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/ContactController.php
<?php

namespace App\Http\Controllers\Schedule;

use Carbon\Carbon;
use Barryvdh\DomPDF\Facade as PDF;
use App\Services\PhoneService;
use App\Exports\ContactsExport;
use App\Services\AddressService;
use App\Services\ContactService;
use App\Services\CategoryService;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Requests\RequestContact;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\RequestContactEdit;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon as SupportCarbon;

class ContactController extends Controller
{
    private $addressService;

    private $categoryService;

    private $contactService;

    private $phoneService;

    public function __construct(
        AddressService $addressService,
        CategoryService $categoryService,
        PhoneService $phoneService,
        ContactService $contactService
    ) {
        $this->addressService = $addressService;

        $this->categoryService = $categoryService;

        $this->phoneService = $phoneService;

        $this->contactService = $contactService;
    }

    /**
     * Retorna a visualização de todos os contatos existentes no banco
     * os quais foram cadastrados pelo usuário autenticado
     *
     * @param
     *
     * @return View
     */
    public function index(Request $request)
    {
       
        $userAuthId = auth()->user()->id;

        if ($request->all()) {
            $startDate = DateTime::createFromFormat('d/m/Y H:i:s', $request->startDate);

            $startDate->format('Y/m/d H:i:s');
            
            $endDate = DateTime::createFromFormat('d/m/Y H:i:s', $request->endDate);

            $endDate->format('Y/m/d H:i:s');

            $contacts = $this->contactService
            ->findContactBetwen('created_at', [$startDate, $endDate]);
        } elseif (!$request->all()) {
            $contacts = $this->contactService->findAllContacts($userAuthId);
        }

        return view('schedule.contacts.index', compact('contacts'));
    }

    /**
     * Retorna o formulário de criação dos contatos
     *
     * @param
     *
     * @return View
     */
    public function create()
    {
        $categories = $this->categoryService->findAllCategoriesCombobox();

        return view('schedule.contacts.create', compact('categories'));
    }


    /**
     * Salva o contato no banco
     *
     * @param RequestContact $request
     *
     * @return View
     */
    public function store(RequestContact $request)
    {
        $data = $request->all();

        $data['user_id'] = auth()->user()->id;

        $request->hasFile('image') ? $data = $this->uploadImage($data, $request) : null;

        $contact = $this->categoryService->createContactByCategory($data);

        $this->addressService->createAddress($data, $contact);

        $this->phoneService->createPhone($data, $contact);

        flash('Contato salvo com sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }


    /**
     * Retorna a visualização da foto de um usuário
     *
     * @param int $idContact
     *
     * @return string
     */
    public function show($idContact)
    {
        $contact = $this->contactService->findContact($idContact);

        return $contact->image;
    }


    /**
     * Retorna a visualização do formulário para edição de determinado contato
     *
     * @param int $idContact
     *
     * @return void
     */
    public function edit($idContact)
    {
        $contact = $this->contactService->findContact($idContact);

        $categories = $this->categoryService->findAllCategories();

        return view('schedule.contacts.edit', compact('contact', 'categories'));
    }


    /**
     * Atualiza determinado contato no banco
     *
     * @param RequestContactEdit $request
     *
     * @param int $idContact
     *
     * @return View
     */
    public function update(RequestContactEdit $request, $idContact)
    {
        $data = $request->all();

        $request->hasFile('image') ? $data = $this->uploadImage($data, $request) : null;

        $this->contactService->updateContact($idContact, $data);

        flash('Contato Atualizado com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Exclui determinado contato do banco de dados
     *
     * @param int $contactId
     *
     * @return View
     */
    public function destroy($contactId)
    {
        $this->phoneService->deletePhoneWhere($contactId);

        $this->addressService->deleteAddressWhere($contactId);

        $this->contactService->deleteContact($contactId);

        flash('Contato Excluído com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Grava foto do contato no banco de dados
     *
     * @param void $data
     *
     * @param object $request
     *
     * @return void
     */
    private function uploadImage($data, $request)
    {
        $image = $request->file('image');

        $data['image'] = $image->store('products', 'public');

        return $data;
    }


    /**
     * Exclui foto do contato no banco de dados e storage
     *
     * @param int $contactId
     *
     * @return View
     */
    public function removePhoto($contactId)
    {
        $contact = $this->contactService->findContact($contactId);

        $photoName = $contact->image;

        if (Storage::disk('public')->exists($photoName)) {
            Storage::disk('public')->delete($photoName);
        }

        $this->contactService->deleteContactPhoto($contactId);

        flash('Foto excluida com sucesso!')->success();

        return redirect()->route('schedule.contacts.edit', $contactId);
    }


    public function exportContacts()
    {
        return Excel::download(new ContactsExport(), 'contacts.xlsx');
    }


    public function printPdf()
    {
        $userAuthId = auth()->user()->id;
        $contacts = $this->contactService->findAllContacts($userAuthId);
        $pdfContact = PDF::loadView('schedule.contacts.index_table_print', compact('contacts'));
        return $pdfContact->download('contatos.pdf');
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/PhoneController.php
<?php

namespace App\Http\Controllers\Schedule;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestPhoneEdit;
use Illuminate\Http\Request;
use App\Services\PhoneService;
use App\Services\ContactService;

class PhoneController extends Controller
{
    protected $phoneService;

    protected $contactService;

    /**
     * Construtor
     */
    public function __construct(PhoneService $phoneService, ContactService $contactService)
    {
        $this->phoneService = $phoneService;

        $this->contactService = $contactService;
    }



    /**
     * Retorna a visualização dos telefones de um usuário
     *
     * @param int $userId
     *
     * @return View
     */
    public function show($contactId)
    {
        $phones = $this->phoneService->findPhoneByContact($contactId);

        $contact = $this->contactService->findContact($contactId);

        return view('schedule.phones.index', compact('phones', 'contact'));
    }

     /**
     * Retorna a visualização do formulário para edição de determinado telefone
     *
     * @param int $phoneId
     *
     * @return void
     */
    public function edit($phoneId)
    {
        $phone = $this->phoneService->findPhone($phoneId);

        return view('schedule.phones.edit', compact('phone'));
    }

    /**
     * Atualiza um determinado telefone no banco
     *
     * @param int $idPhone
     *
     * @param Request $request
     *
     * @return View
     */
    public function update(RequestPhoneEdit $request, $idPhone)
    {
        $data = $request->all();
          
        $this->phoneService->updatePhone($data, $idPhone);

        flash('Telefone Atualizado com Sucesso!')->success();

       // return redirect()->route('schedule.phones.show', ['phone' => $contactId]);

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Exclui um determinado telefone no banco
     *
     * @param int $phoneId
     *
     * @return View
     */
    public function destroy($phoneId)
    {
        $this->phoneService->deletePhone($phoneId);

        flash('Telefone Excluido com Sucesso')->success();

        return redirect()->route('schedule.contacts.index');
    }
}

vexpenses_agenda/resources/views/schedule/contacts/create.blade.php
@extends('layouts.app')

@section('content')
<h4>Dados pessoais do contato</h4>
  {{ Form::open(['route' => 'schedule.contacts.store', 'data-validate', 
   'files' => true, 'method' => "POST", 'class="form-group"']) }}
    @csrf
    @include('schedule.contacts.fields')
  {!! Form::close() !!}
@endsection

vexpenses_agenda/resources/views/schedule/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
  @if($contact->image != "")
  <div class="form-group row">
    <div class="col-3">
      <img src="{{asset('storage/'.$contact->image)}}" alt="" class="img-thumbnail">
      <form action="{{route('schedule.photo.remove',$contact->id)}}" method="post">
         @csrf
         <button type="submit" class="btn btn-sm btn-danger mt-1">
           Remover
         </button>
      </form>
    </div>
  </div>
  @endif
  <form action="{{route('schedule.contacts.update', ['contact' => $contact->id ] )}}"
     class="form-group" method="POST" enctype="multipart/form-data">
    @csrf
    @method('put')
      <div class="form-group row">
        <div class="col-md-6">
          <label>Nome Contato</label>
        <input type="text" name="name" value="{{$contact->name}}" class="form-control 
         @error('name') is-invalid @enderror">
            @error('name')
            <div class="invalid-feedback">
              {{$message}}
            </div>
            @enderror
      </div>
        <div class="col-md-6">
          <label>Email Contato</label>
          <input type="email" name="email" value="{{$contact->email}}" class="form-control 
          @error('email') is-invalid @enderror">
           @error('email')
             <div class="invalid-feedback">
                {{$message}}
             </div>
           @enderror
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-6">
          <label>Categoria</label>
          <select name="category_id" id="category"  class="form-control 
          @error('category_id') is-invalid  @enderror">
            <option value="">selecione uma categoria ..</option>
            @foreach ($categories as $category )
            <option value="{{ $category->id }}" {{$contact->category_id == $category->id ?
             "selected" : "" }}>{{ $category->category_name }}</option>
            @endforeach
          </select>
          @error('category_id')
           <div class="invalid-feedback">
             {{$message}}
           </div>
          @enderror
        </div>
       
        <div class="col-md-6">
          <label>Foto Contato</label>
          <input type="file" name="image" value="" class="form-control">   
        </div>
      </div>
    <button class="btn btn-success" type="submit">Salvar</button>
   </form>

@endsection

vexpenses_agenda/resources/views/schedule/contacts/fields.blade.php
<div class="form-group row">
    <div class="col-md-6">
     {!! Form::textField('name', 'Nome Usuário', null,
     [
      'data-rule-required' => 'true',
       'class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : null)
     ]) !!}
     @error('name')
      <div class="invalid-feedback">
        {{$message}}
      </div>
     @enderror
  </div>
    <div class="col-md-6">
      {!! Form::textField('email', 'Email Usuário', null,
      [
       'data-rule-required' => 'true',
       'type' => 'email',
       'class' => 'form-control'. ($errors->has('email') ? ' is-invalid' : null)
      ]) !!}
       @error('email')
         <div class="invalid-feedback">
            {{$message}}
         </div>
       @enderror
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-6">
      {!! Form::selectField('category_id', 'Categoria',
        $categories,
        null,
        [
          'data-input' => 'selectize',
          'class' => 'form-control'. ($errors->has('category_name') ? ' is-invalid' : null)
        ]) !!}
        @error('category_name')
          <div class="invalid-feedback">
            {{$message}}
          </div>
        @enderror
    </div>

    <div class="col-md-6">
      {!! Form::inputFileImages('image','Foto Usuário',
       [
         'class' => 'form-control',
         'type'  => 'file'
       ]) !!}
    </div>
  </div>

  <hr class="border border-secondary">
  <h4>Telefones do contato</h4>
  <div class="form-group row">
    <div class="col-md-6">
      {!! Form::textField(
        'mobile_phone[]','Celular', null,
        [
          'data-rule-required' => 'true',
          'data-rule-fone' => 'true',
          'class' => 'form-control mask mask__fone'
        ]
      )!!}
    </div>
    <div class="col-md-6">
      {!! Form::textField(
        'phone[]','Telefone', null,
        [
          'data-rule-required' => 'true',
          'data-rule-fone' => 'true',
          'class' => 'form-control mask mask__fone',
         
        ]
      )!!}
    </div> 
  </div>

  <!-- inserir mais de um telefone -->
  <div id="morePhones">
    <div class="morePhones">
    </div>     
  <div>

 <div id="btnsPhone">
   <div class="btn-group">
     <button class="btn btn-info" id="addPhones" value="1">
      <i class="fa fa-plus"></i>
      Adicionar Telefone
     </button>  
   </div>  
 </div>

  <hr class="border border-secondary">
  <h4>Endereços do contato</h4>
  <div class="form-group row">

    <div class="col-md-2">
      {!! Form::textField(
        'cep[]','Cep', null,
        [
          'id' => '1',
          'data-rule-required' => 'true',
          'class' => 'form-control cep'
        ]
      )!!}
    </div> 

    <div class="col-md-4">
      {!! Form::textField(
        'street[]','Rua', null,
        [
          'id' => 'street1',
          'data-rule-required' => 'true',
          'class' => 'form-control'
        ]
      )!!}
   </div>

   <div class="col-md-2">
      {!! Form::textField(
        'number[]','Número', null,
        [
          'data-rule-required' => 'true',
          'class' => 'form-control'
        ]
      )!!}
   </div> 
  
    <div class="col-md-4">
      {!! Form::textField(
        'neighborhood[]','Bairro', null,
        [
          'id' => 'neighborhood1',
          'data-rule-required' => 'true',
          'class' => 'form-control'
        ]
      )!!}
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-4">
      {!! Form::textField(
        'city[]','Cidade', null,
        [
          'id' => 'city1',
          'data-rule-required' => 'true',
          'class' => 'form-control'
        ]
      )!!}
    </div>
    <div class="col-md-2">
      {!! Form::textField(
        'state[]','Estado', null,
        [
          'id' => 'state1',
          'data-rule-required' => 'true',
          'class' => 'form-control'
        ]
      )!!}
    </div> 
  </div>

     <!-- inserir mais de um endereço -->
     <div id="moreAddress">
      <div class="moreAddress">
      </div>     
     <div>

  <div id="btnsAddress">
    <div class="btn-group" >
      <button class="btn btn-info" id="add" value="1">
       <i class="fa fa-plus"></i>
       Adicionar Endereços
      </button>    
    </div>   
  </div>
     

  <hr class="border border-secondary">


<button class="btn btn-success" type="submit">Cadastrar</button>

vexpenses_agenda/resources/views/schedule/contacts/index.blade.php
@extends('layouts.app')

@section('content')


<a class="btn btn-info float-left"
        href="{{route('schedule.contacts.create')}}">
        Novo Contato
</a>
<div class="d-flex flex-row-reverse">
       <a class="btn btn-danger ml-1 mb-1 p-2"
       href="{{route('schedule.contacts.print')}}">
        Imprimir <i class="fas fa-file-pdf"></i>
      </a>  
       <a class="btn btn-success p-2 mb-1"
          href="{{route('schedule.contacts.export')}}">
           Exportar <i class="fas fa-file-excel"></i>
       </a>  
</div>

<form action="{{route('schedule.contacts.index')}}" method="get">
<div class="form-group row">
       <div class="col-md-3 offset-6">
         {!! Form::dateField(
           'startDate','Data Inicio', null,
           [
             'data-input' => 'datetimepicker',
             'data-rule-required' => 'true',
             'class' => 'form-control'
           ]
         )!!}
      </div>
      <div class="col-md-3">
       {!! Form::dateField(
         'endDate','Data Fim', null,
         [
           'data-input' => 'datetimepicker',
           'data-rule-required' => 'true',
           'class' => 'form-control'
         ]
       )!!}
    </div>
    
</div>
<div class="btn group offset-11">
       <button class="btn btn-success">Buscar</button>
</div>
</form>
 
@include('schedule.contacts.index_table')

@include('schedule.phones.modals.show_phone')

@include('schedule.phones.modals.edit_phone')

@include('schedule.contacts.modals.photo_contact')

@include('schedule.adresses.modals.show_address')

@include('schedule.adresses.modals.edit_address')


   
@endsection

vexpenses_agenda/resources/views/schedule/contacts/index_table.blade.php
<div class="table table-reponsive">
    <table class="table table-striped table-hover data-table" data-page-length='5' >
        <thead class="thead-dark">
            <th>Id Contato</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Categoria</th>
            <th>Foto</th>
            <th>Telefones</th>
            <th>Endereços</th>
            <th>Ações</th>
        </thead>
        <tbody>
            @foreach ($contacts as $contact)
            <tr>
                <td>{{$contact->id}}</td>  
                <td>{{ucwords(strtolower($contact->name))}}</td>  
                <td>{{$contact->email}}</td>   
                <td>{{$contact->category}}</td>
                <th>
                    <button class="btn btn-primary open-modal-photo-js" data-toggle="modal" 
                    data-target="#photoModal" data-target-content="#showContactPhoto"
                    data-target-attr="src"
                    data-href="{{route('schedule.contacts.show', $contact->id)}}"
                    >
                        <i class="fa fa-user"></i>
                    </button>
                </th>
                <td>                            
                  <button class="btn btn-primary open-modal-js" 
                  data-toggle="modal" data-target="#phoneModal" data-target-content="#phoneTable"
                  data-href="{{route('schedule.phones.show',$contact->id)}}">
                       <i class="fa fa-phone"></i>
                   </button>
                </td>
                <td>
                    <button class="btn btn-primary open-modal-js" 
                    data-toggle="modal" data-target="#addressModal" data-target-content="#addressTable"
                    data-href="{{route('schedule.adresses.show', $contact->id)}}">
                        <i class="fa fa-home"></i>
                    </button>
                </td>
                <td>
                   <div class="btn-group">
                       <a class="btn btn-sm btn-warning" href="{{route('schedule.contacts.edit',
                       ['contact'=>$contact->id])}}" >
                           <i class="fa fa-pencil"></i> Editar
                       </a>
                   </div> 

                   <div class="btn-group">
                    <form action="{{route('schedule.contacts.destroy', $contact->id)}}"
                     method="post" >
                     @csrf
                     @method('delete')
                     <button type="submit" class="btn btn-sm btn-danger" >
                         <i class="fa fa-trash"></i> Excluir
                     </button>
                    </form>
                   </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

vexpenses_agenda/resources/views/schedule/contacts/index_table_print.blade.php
<div class="table table-reponsive">
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <th>Id Contato</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Categoria</th>
            <tr style="page-break-after:always;"></tr>
        </thead>
        <br>
        <tbody>
            @foreach ($contacts as $contact)
            <tr>
                <td>{{$contact->id}}</td>  
                <td>{{ucwords(strtolower($contact->name))}}</td>  
                <td>{{$contact->email}}</td>   
                <td>{{$contact->category}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>