vexpenses_agenda/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Jobs\SendEmailJob;
use App\Mail\SendEmail;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::prefix('schedule/')->name('schedule.')->namespace('Schedule')->group(function () {

    Route::resource('categories', 'CategoryController');

    Route::resource('phones', 'PhoneController');

    Route::resource('adresses', 'AddressController');

    Route::resource('contacts', 'ContactController');

    Route::post('photos/remove/{contactId}', 'ContactController@removePhoto')->name('photo.remove');

    Route::get('exports', 'ContactController@exportContacts')->name('contacts.export');

    Route::get('print', 'ContactController@printPdf')->name('contacts.print');

    Route::get('contactsByDate', 'ContactController@showContactByDate')->name('contacts.byDate');

   

});

vexpenses_agenda/app/Http/Controllers/Schedule/AddressController.php
<?php

namespace App\Http\Controllers\Schedule;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestAddressEdit;
use App\Services\AddressService;
use App\Services\ContactService;
use Illuminate\Http\Request;

class AddressController extends Controller
{

    protected $addressService;

    protected $userService;

    protected $contactService;
   
     /**
     * Construtor
     */
    public function __construct(AddressService $addressService, ContactService $contactService)
    {
         $this->addressService = $addressService;

         $this->contactService = $contactService;
    }
  

    /**
     * Retorna a visualização dos endereços de um usuário
     *
     * @param int $userId
     *
     * @return View
     */
    public function show($contactId)
    {
        $adresses = $this->addressService->findAddressByContact($contactId);

        $contact = $this->contactService->findContact($contactId);

        return view('schedule.adresses.index', compact('adresses', 'contact'));
    }

     /**
     * Retorna a visualização do formulário para edição de determinado endereço
     *
     * @param int $addressId
     *
     * @return void
     */
    public function edit($addressId)
    {
        $address = $this->addressService->findAddress($addressId);

        return view('schedule.adresses.edit', compact('address'));
    }

   /**
     * Atualiza um determinado endereço no banco
     *
     * @param int $addressId
     *
     * @param Request $request
     *
     * @return View
     */
    public function update(RequestAddressEdit $request, $addressId)
    {
        $data = $request->all();

        $this->addressService->updateAddress($data, $addressId);

        flash('Endereço Atualizado com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Exclui um determinado endereço no banco
     *
     * @param int $addressId
     *
     * @return View
     */
    public function destroy($addressId)
    {
        $this->addressService->deleteAddress($addressId);

        flash('Endereço Excluído com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/CategoryController.php
<?php

namespace App\Http\Controllers\Schedule;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestCategory;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use App\Http\Middleware\CheckContact;

class CategoryController extends Controller
{
     private $categoryService;
    
    /**
    * Construtor
    */
    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;

        $this->middleware('checkContact', ['only' => ['destroy']]);

        $this->middleware('checkCategoryName', ['only' => ['store','update']]);
    }

    /**
     * Retorna a visualização de todas as categorias existentes no banco
     *
     * @param
     *
     * @return View
     */
    public function index()
    {
        $categories = $this->categoryService->findAllCategories();

        return view('schedule.categories.index', compact('categories'));
    }

    /**
     * Retorna o formulário de criação das categorias
     *
     * @param
     *
     * @return View
     */
    public function create()
    {
        return view('schedule.categories.create');
    }

    /**
     * Salva a categoria no banco
     *
     * @param Request $request
     *
     * @return View
     */
    public function store(RequestCategory $request)
    {
         
          $data = $request->all();

          $this->categoryService->createCategory($data);

          flash('Categoria cadastrada com sucesso!')->success();

          return redirect()->route('schedule.categories.index');
    }


   
     /**
     * Retorna a visualização do formulário para edição de determinada categoria
     *
     * @param int $category
     *
     * @return void
     */
    public function edit($category)
    {
        $category = $this->categoryService->findCategory($category);

        return view('schedule.categories.edit', compact('category'));
    }

    /**
     * Atualiza determinada categoria no banco
     *
     * @param Request $request
     *
     * @param int $id
     *
     * @return View
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $this->categoryService->updateCategory($data, $id);

        flash('Categoria Atualizada com sucesso!')->success();

        return redirect()->route('schedule.categories.index');
    }

   /**
     * Exclui determinada categoria do banco de dados
     *
     * @param int $id
     *
     * @return View
     */
    public function destroy($id)
    {
        $this->categoryService->deleteCategory($id);

        flash('Categoria Excluida com Sucesso!')->success();

        return redirect()->route('schedule.categories.index');
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/ContactController.php
<?php

namespace App\Http\Controllers\Schedule;

use Carbon\Carbon;
use Barryvdh\DomPDF\Facade as PDF;
use App\Services\PhoneService;
use App\Exports\ContactsExport;
use App\Services\AddressService;
use App\Services\ContactService;
use App\Services\CategoryService;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Requests\RequestContact;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\RequestContactEdit;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon as SupportCarbon;

class ContactController extends Controller
{
    private $addressService;

    private $categoryService;

    private $contactService;

    private $phoneService;

    public function __construct(
        AddressService $addressService,
        CategoryService $categoryService,
        PhoneService $phoneService,
        ContactService $contactService
    ) {
        $this->addressService = $addressService;

        $this->categoryService = $categoryService;

        $this->phoneService = $phoneService;

        $this->contactService = $contactService;
    }

    /**
     * Retorna a visualização de todos os contatos existentes no banco
     * os quais foram cadastrados pelo usuário autenticado
     *
     * @param
     *
     * @return View
     */
    public function index(Request $request)
    {
       
        $userAuthId = auth()->user()->id;

        if ($request->all()) {
            $startDate = DateTime::createFromFormat('d/m/Y H:i:s', $request->startDate);

            $startDate->format('Y/m/d H:i:s');
            
            $endDate = DateTime::createFromFormat('d/m/Y H:i:s', $request->endDate);

            $endDate->format('Y/m/d H:i:s');

            $contacts = $this->contactService
            ->findContactBetwen('created_at', [$startDate, $endDate]);
        } elseif (!$request->all()) {
            $contacts = $this->contactService->findAllContacts($userAuthId);
        }

        return view('schedule.contacts.index', compact('contacts'));
    }

    /**
     * Retorna o formulário de criação dos contatos
     *
     * @param
     *
     * @return View
     */
    public function create()
    {
        $categories = $this->categoryService->findAllCategoriesCombobox();

        return view('schedule.contacts.create', compact('categories'));
    }


    /**
     * Salva o contato no banco
     *
     * @param RequestContact $request
     *
     * @return View
     */
    public function store(RequestContact $request)
    {
        $data = $request->all();

        $data['user_id'] = auth()->user()->id;

        $request->hasFile('image') ? $data = $this->uploadImage($data, $request) : null;

        $contact = $this->categoryService->createContactByCategory($data);

        $this->addressService->createAddress($data, $contact);

        $this->phoneService->createPhone($data, $contact);

        flash('Contato salvo com sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }


    /**
     * Retorna a visualização da foto de um usuário
     *
     * @param int $idContact
     *
     * @return string
     */
    public function show($idContact)
    {
        $contact = $this->contactService->findContact($idContact);

        return $contact->image;
    }


    /**
     * Retorna a visualização do formulário para edição de determinado contato
     *
     * @param int $idContact
     *
     * @return void
     */
    public function edit($idContact)
    {
        $contact = $this->contactService->findContact($idContact);

        $categories = $this->categoryService->findAllCategories();

        return view('schedule.contacts.edit', compact('contact', 'categories'));
    }


    /**
     * Atualiza determinado contato no banco
     *
     * @param RequestContactEdit $request
     *
     * @param int $idContact
     *
     * @return View
     */
    public function update(RequestContactEdit $request, $idContact)
    {
        $data = $request->all();

        $request->hasFile('image') ? $data = $this->uploadImage($data, $request) : null;

        $this->contactService->updateContact($idContact, $data);

        flash('Contato Atualizado com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Exclui determinado contato do banco de dados
     *
     * @param int $contactId
     *
     * @return View
     */
    public function destroy($contactId)
    {
        $this->phoneService->deletePhoneWhere($contactId);

        $this->addressService->deleteAddressWhere($contactId);

        $this->contactService->deleteContact($contactId);

        flash('Contato Excluído com Sucesso!')->success();

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Grava foto do contato no banco de dados
     *
     * @param void $data
     *
     * @param object $request
     *
     * @return void
     */
    private function uploadImage($data, $request)
    {
        $image = $request->file('image');

        $data['image'] = $image->store('products', 'public');

        return $data;
    }


    /**
     * Exclui foto do contato no banco de dados e storage
     *
     * @param int $contactId
     *
     * @return View
     */
    public function removePhoto($contactId)
    {
        $contact = $this->contactService->findContact($contactId);

        $photoName = $contact->image;

        if (Storage::disk('public')->exists($photoName)) {
            Storage::disk('public')->delete($photoName);
        }

        $this->contactService->deleteContactPhoto($contactId);

        flash('Foto excluida com sucesso!')->success();

        return redirect()->route('schedule.contacts.edit', $contactId);
    }


    public function exportContacts()
    {
        return Excel::download(new ContactsExport(), 'contacts.xlsx');
    }


    public function printPdf()
    {
        $userAuthId = auth()->user()->id;
        $contacts = $this->contactService->findAllContacts($userAuthId);
        $pdfContact = PDF::loadView('schedule.contacts.index_table_print', compact('contacts'));
        return $pdfContact->download('contatos.pdf');
    }
}

vexpenses_agenda/app/Http/Controllers/Schedule/PhoneController.php
<?php

namespace App\Http\Controllers\Schedule;

use App\Http\Controllers\Controller;
use App\Http\Requests\RequestPhoneEdit;
use Illuminate\Http\Request;
use App\Services\PhoneService;
use App\Services\ContactService;

class PhoneController extends Controller
{
    protected $phoneService;

    protected $contactService;

    /**
     * Construtor
     */
    public function __construct(PhoneService $phoneService, ContactService $contactService)
    {
        $this->phoneService = $phoneService;

        $this->contactService = $contactService;
    }



    /**
     * Retorna a visualização dos telefones de um usuário
     *
     * @param int $userId
     *
     * @return View
     */
    public function show($contactId)
    {
        $phones = $this->phoneService->findPhoneByContact($contactId);

        $contact = $this->contactService->findContact($contactId);

        return view('schedule.phones.index', compact('phones', 'contact'));
    }

     /**
     * Retorna a visualização do formulário para edição de determinado telefone
     *
     * @param int $phoneId
     *
     * @return void
     */
    public function edit($phoneId)
    {
        $phone = $this->phoneService->findPhone($phoneId);

        return view('schedule.phones.edit', compact('phone'));
    }

    /**
     * Atualiza um determinado telefone no banco
     *
     * @param int $idPhone
     *
     * @param Request $request
     *
     * @return View
     */
    public function update(RequestPhoneEdit $request, $idPhone)
    {
        $data = $request->all();
          
        $this->phoneService->updatePhone($data, $idPhone);

        flash('Telefone Atualizado com Sucesso!')->success();

       // return redirect()->route('schedule.phones.show', ['phone' => $contactId]);

        return redirect()->route('schedule.contacts.index');
    }

    /**
     * Exclui um determinado telefone no banco
     *
     * @param int $phoneId
     *
     * @return View
     */
    public function destroy($phoneId)
    {
        $this->phoneService->deletePhone($phoneId);

        flash('Telefone Excluido com Sucesso')->success();

        return redirect()->route('schedule.contacts.index');
    }
}

vexpenses_agenda/resources/views/schedule/adresses/edit.blade.php
<form action="{{route('schedule.adresses.update', ['adress' => $address->id])}}"
     class="form-group" method="POST" data-validate="true">
    @csrf
    @method('put')
      <div class="form-group row">

        <div class="col-md-2">
          <div class="form-group">
            <label>Cep</label>
            <input type="text" name="cep" id="1"  value="{{$address->cep}}" 
            class="cep form-control" data-rule-required="true">
            @error('cep')
            <div class="invalid-feedback">
              {{$message}}
            </div>
            @enderror
          </div>
        </div> 

        <div class="col-md-4">
         <div class="form-group">
          <label>Rua</label>
          <input type="text" name="street" id="street1" value="{{$address->street}}"
           class="form-control" data-rule-required="true">       
             @error('street')
             <div class="invalid-feedback">
               {{$message}}
              </div>
             @enderror
         </div>
        </div>

        <div class="col-md-2">
          <div class="form-group">
            <label>Número</label>
            <input type="text" name="number" value="{{$address->number}}"
            class="form-control" data-rule-required="true">
            @error('number')
            <div class="invalid-feedback">
              {{$message}}
              </div>
            @enderror
          </div>
        </div> 
  
        <div class="col-md-4">
          <div class="form-group">
            <label>Bairro</label>
            <input type="text" name="neighborhood" id="neighborhood1"
            value="{{$address->neighborhood}}" 
            class="form-control" data-rule-required="true">
            @error('neighborhood')
            <div class="invalid-feedback">
              {{$message}}
            </div>
            @enderror
          </div>
        </div>

      </div>

      <div class="form-group row">

        <div class="col-md-4">
          <div class="form-group">
            <label>Cidade</label>
            <input type="text" name="city" id="city1" value="{{$address->city}}" 
            class="form-control" data-rule-required="true"> 
            @error('city')
            <div class="invalid-feedback">
              {{$message}}
            </div>
            @enderror
          </div>
        </div>

        <div class="col-md-2">
          <div class="form-group">
            <label>Estado</label>
            <input type="text" name="state" id="state1" value="{{$address->state}}" 
            class="form-control" data-rule-required="true">
            @error('state')
            <div class="invalid-feedback">
              {{$message}}
            </div>
            @enderror
          </div>
        </div> 

      </div>

    <button class="btn btn-success" type="submit">Salvar</button>
   </form>
   

vexpenses_agenda/resources/views/schedule/adresses/index.blade.php
<div class="table table-responsive">
    <table class="table table-hover">
        <thead>
            <th>Id Endereço</th>
            <th>Rua</th>
            <th>Numero</th>
            <th>Bairro</th>
            <th>Cep</th>
            <th>Cidade</th>
            <th>Estado</th>
            <th>Ações</th>
        </thead>
        <tbody>
            @foreach ($adresses as $address)
            <tr>
              <td>{{$address->id}}</td>
              <td>{{ucwords(strtolower($address->street))}}</td>
              <td>{{$address->number}}</td>
              <td>{{ucwords(strtolower($address->neighborhood))}}</td>
              <td>{{$address->cep}}</td>
              <td>{{ucwords(strtolower($address->city))}}</td>
              <td>{{ucwords(strtolower($address->state))}}</td>
              <td>
                <div class="btn-group">
                    <button class="open-modal-js btn btn-sm btn-warning" data-toggle="modal" 
                    data-target="#editAddressModal" data-target-content="#editAddress"
                    data-href="{{route('schedule.adresses.edit',$address->id)}}">
                    Editar
                    </button>    
                </div>

                <div class="btn-group mt-1">
                     <form action="{{route('schedule.adresses.destroy', ['adress' => $address->id])}}"
                      method="POST">
                        @csrf  
                        @method('delete')
                        <button class="btn btn-sm btn-danger" type="submit">
                          Excluir
                        </button>
                      </form>
                </div>
              </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {{$adresses->links()}}
</div>
<script src="{{ asset('assets/js/app.js') }}"></script>